### PR TITLE
Add zsh fish bash completion support

### PR DESCRIPTION
**Pull request by niT-Tin**
Add zsh fish bash completion support
---
Place the completion file of the corresponding shell in the completion folder in the specified location

### CODE REVIEW

**Comment by niT-Tin** [comment]
and the specific effect is as follows
bash
lsdbash
zsh
lsdzsh
fish
lsdfish

**Comment by nim65s** [comment]
Hi,

What is the point of adding those generated files here ?

I think this should be closed in favor of #861, or something like that.

**Comment by niT-Tin** [comment]
> 

Oh, thank you for your reminder. I did not notice that there was already a completion operation, but using LSD on my computer did not have this effect, so I wrote these shell completion myself. If there is no problem running lsd completion on someone else, then this pr can indeed be closed

**Comment by nim65s** [comment]
Arch already provide them : https://gitlab.archlinux.org/archlinux/packaging/packages/lsd/-/blob/main/PKGBUILD#L42-L44
Nix too: https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/lsd/default.nix#L28

You probably just need to set `SHELL_COMPLETIONS_DIR`

**Comment by niT-Tin** [comment]
> Arch already provide them : https://gitlab.archlinux.org/archlinux/packaging/packages/lsd/-/blob/main/PKGBUILD#L42-L44 Nix too: https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/lsd/default.nix#L28
> 
> You probably just need to set `SHELL_COMPLETIONS_DIR`

Wow, thanks, I'll try

**Comment by zwpaper** [comment]
https://github.com/lsd-rs/lsd/blob/8acaabec723cdd71b498212c8a47ac952d022738/build.rs#L32-L35 

we already support this

/close

**Pull request closed without merging**
