### PR TITLE
#1052 fix lsd pipe output

### PR DESCRIPTION
**Pull request by WangMengabc**
---
#### TODO

- [x] Use `cargo fmt`
- [x] Add necessary tests
- [x] Update default config/theme in README (if applicable)
- [x] Update man page at lsd/doc/lsd.md (if applicable)

### CODE REVIEW

**Comment by GottZ** [comment]
closes #1072

**Review by GottZ — APPROVED** [review]

**Comment by GottZ** [comment]
@meain hey there. can you please take a look at this, as @zwpaper seems to be on vacation off github for a month by now?

**Comment by zwpaper** [comment]
sorry for the delay, some personal issues have trapped me recently. I will look into PRs in following days

**Comment by GottZ** [comment]
> sorry for the delay, some personal issues have trapped me recently.

welcome back!

**Comment by zwpaper** [comment]
the change lgtm, but we may have some issues on tests, I am working on it, and will merge after I fix the tests

**Comment by GottZ** [comment]
I'm at FrOSCon right now, lsd just got presented at a [talk](https://programm.froscon.org/2024/events/3125.html) where I just had to mention this bug.

**Comment by zwpaper** [comment]
Hi @GottZ, thanks so much for provide the info about the talk, it was excited to know about people using lsd.

as for the bug, I beleive this PR has fix it and it should be good to go now, can you hekp checking the lsd from https://github.com/WangMengabc/lsd/tree/master, or I can build a binary for you if needed.

**Comment by GottZ** [comment]
> as for the bug, I beleive this PR has fix it and it should be good to go now, can you hekp checking the lsd from https://github.com/WangMengabc/lsd/tree/master, or I can build a binary for you if needed.

image

it's flawless. thanks!

**Comment by zwpaper** [comment]
thanks for the help, let's create a new release for this

**Pull request merged**
