### PR TITLE
Make `.profile` have the same icon as `profile`

### PR DESCRIPTION
**Pull request by alichtman**
- [x] Use `cargo fmt`
- [x] Add necessary tests
- [x] Add changelog entry
- [x] Update default config/theme in README (if applicable)
- [x] Update man page at lsd/doc/lsd.md (if applicable)

### CODE REVIEW

**Comment by alichtman** [comment]
@zwpaper Any chance you could stamp this too?

**Comment by zwpaper** [comment]
hi @alichtman, sorry for missing the PR, I was kinda busy recently.

/lgtm
/approve

**Comment by alichtman** [comment]
No problem! Thanks!

**Pull request merged**
