### PR TITLE
CI: build for aarch64-macos and aarch64-windows

### PR DESCRIPTION
**Pull request by CarterLi**
Build for more platforms.

I know very little about rust. Hopefully it works

### CODE REVIEW

**Comment by zwpaper** [comment]
Hi @CarterLi, feel free to raise PRs, it does not have to be familiar with Rust to contribute 😉

**Comment by CarterLi** [comment]
Test failed because of incompatible platforms. Maybe we should skip the tests on arm64, but I dont know how to do that

**Comment by meain** [comment]
@CarterLi I have not looked much into the PR, but [here](https://github.com/meain/lsd/blob/d1cf72c96851b39b5b73521c3ed2c87a11fc954f/.github/workflows/CICD.yml#L164) is how we are skipping test for arm currently.

**Comment by meain** [comment]
@CarterLi I haven't looked into the PR, but [here](https://github.com/meain/lsd/blob/d1cf72c96851b39b5b73521c3ed2c87a11fc954f/.github/workflows/CICD.yml#L164) is how we do it for arm.

I haven't tried it, but I think this should work:

``` diff
diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
index a888510..b771d73 100644
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -162,7 +162,7 @@ jobs:
         echo set-output name=CARGO_USE_CROSS::${CARGO_USE_CROSS:-<empty>/false}
         echo ::set-output name=CARGO_USE_CROSS::${CARGO_USE_CROSS}
         # * test only binary for arm-type targets
-        unset CARGO_TEST_OPTIONS ; case ${{ matrix.job.target }} in arm-* | aarch64-*-linux-*) CARGO_TEST_OPTIONS="--bin ${PROJECT_NAME}" ;; esac;
+        unset CARGO_TEST_OPTIONS ; case ${{ matrix.job.target }} in arm-* | aarch64-*) CARGO_TEST_OPTIONS="--bin ${PROJECT_NAME}" ;; esac;
         echo set-output name=CARGO_TEST_OPTIONS::${CARGO_TEST_OPTIONS}
         echo ::set-output name=CARGO_TEST_OPTIONS::${CARGO_TEST_OPTIONS}
         # * strip executable?
```

**Comment by CarterLi** [comment]
Thanks @meain, fixed

**Pull request closed without merging**
