### PR TITLE
allow directroy-only + depth, fix #747

### LINKED ISSUE #747: lsd --directory-only --tree --depth 2
- os: `Darwin`, `Linux`
- `lsd --version`: `lsd 0.22.0`
- `echo $TERM`: `xterm-256color`
- `echo $LS_COLORS`: _irrelevant_

## Expected behavior
`tree -dL 2` shows directory structure with depth of 2.

## Actual behavior
`lsd --directory-only --tree --depth 2` fails with error:
```
error: The argument '--depth <num>...' cannot be used with '--directory-only'

USAGE:
    lsd --color <color>... --date <date>... --depth <num>... --directory-only --hyperlink <hyperlink>... --icon <icon>... --icon-theme <icon-theme>... --ignore-glob <pattern>... --permission <permission>... --size <size>... --tree

For more information try --help
```

### PR DESCRIPTION
**Pull request by nim65s**
Hi again,

This fix #747.

---
#### TODO

- [x] Use `cargo fmt`
- [x] Add necessary tests
- [x] Add changelog entry
- [x] Update default config/theme in README (if applicable)
- [x] Update man page at lsd/doc/lsd.md (if applicable)

### CODE REVIEW

**Comment by pedropombeiro** [comment]
Can we have this merged? It would be great to have this behavior, as it would greatly improve performance when using lsd as a previewer in vifm.

**Comment by zwpaper** [comment]
hi all, sorry for the late reply, let's get this merged after CI passwd

**Comment by pedropombeiro** [comment]
> hi all, sorry for the late reply, let's get this merged after CI passwd

@zwpaper looks like a couple of Windows jobs failed.

**Comment by pedropombeiro** [comment]
@zwpaper is this blocked? It would be great to have this merged and released.

**Pull request merged**
